### ISSUE TITLE
YMMモードで、テンプレート名を設定できない。

### ISSUE THREAD

**Issue by minotto165** [Garech-mas/RPPtoEXO-ver2.0#1]
v2.08から、YMMモードにした際に保存テンプレート名を設定できなくなってしまいました。
![image](https://github.com/user-attachments/assets/7068f4d6-50cf-4c93-b784-af960df271bb)

**Comment by Garech-mas** [comment]
RPPtoEXOによってテンプレート欄が埋まらないようにするための対応です（現時点では仕様）

YMM4がテンプレートファイル（.ymmt）を扱えるようになり、生成テンプレートがすぐ適用できる状態となっているため、わざわざ別名テンプレートとして保存する必要はないと思っております。

なお、デフォルトで出力させるテンプレート名に関しては　ソフト上部「生成設定」→「保存テンプレート名を変更」から設定できるようにしています。
